version: '2'
services:

    phpminds-nginx:
        build: docker/nginx
        image: phpminds-nginx
        restart: always
        hostname: phpminds.docker
        depends_on:
               - db
        ports:
            - 80:80
            - 443:443
        environment:
            - VIRTUAL_HOST=phpminds.docker
            - VIRTUAL_PORT=80
        volumes:
            - .:/app


    phpminds-php:
        build: docker/php
        image: phpminds-php:php71
        restart: always
        volumes:
            - .:/app
    db:
        build: docker/mysql
        image: phpminds-db:mysql5.7
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: Admin123
            MYSQL_DATABASE: phpminds
            MYSQL_USER: root
            MYSQL_PASSWORD: Admin123
        volumes:
            - ./docker/.data/db:/var/lib/mysql
            - .:/app
