version: '2'
services:

    phpminds-nginx:
        build: docker/nginx
        #restart: always
        ports:
            - 80:80
        environment:
            - VIRTUAL_HOST=phpminds.dev
            - VIRTUAL_PORT=80
        volumes:
            - .:/app

    phpminds-php:
        build: docker/php
        restart: always
        volumes:
            - .:/app
    db:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: notifications
            MYSQL_USER: notifications
            MYSQL_PASSWORD: notifications
        volumes:
            - ./docker/.data/db:/var/lib/mysql

