##################################################
# Generated by phansible.com
##################################################

#If your Vagrant version is lower than 1.5, you can still use this provisioning
#by commenting or removing the line below and providing the config.vm.box_url parameter,
#if it's not already defined in this Vagrantfile. Keep in mind that you won't be able
#to use the Vagrant Cloud and other newer Vagrant features.
Vagrant.require_version ">= 1.5"

Vagrant.configure("2") do |config|

        config.vm.provider :virtualbox do |v|
            v.name = "phpminds"
            v.customize [
                "modifyvm", :id,
                "--name", "phpminds",
                "--memory", 512,
                "--natdnshostresolver1", "on",
                "--cpus", 1,
            ]
        end

        config.vm.box = 'bento/centos-7.1'

        config.vm.network :private_network, ip: "192.168.32.52", auto_config: false, auto_correct: true
        config.vm.network :forwarded_port, host: 15672, guest: 15672
        config.ssh.forward_agent = true
        config.vm.synced_folder "./", "/srv", type: "nfs"



    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.ssh.pty = true
    #############################################################
    # Ansible provisioning (you need to have ansible installed)
    #############################################################
   

    config.vm.provision "shell",
    inline: "yum clean all"

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        ansible.inventory_path = "ansible/inventories/dev"
        ansible.limit = 'all'
    end

    
end
