---
# application tasks to be customized and to run after the main provision


- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

- name: Install vendors
  shell: /usr/local/bin/composer install -d /srv

- name: Run DB migrations
  shell: cd /srv && /srv/vendor/bin/phinx migrate -e {{ app.env }}